version: '3.6'
services:
  Elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: elasticsearch
    restart: always
    volumes:
    - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node    
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: DkIedPPSCb
      xpack.security.enabled: true
      node.name: elasticsearch
    ports:
    - '9200:9200'
    - '9300:9300'
    networks:
      - elk

  Logstash:
    image: docker.elastic.co/logstash/logstash:8.3.3
    container_name: logstash
    restart: always
    volumes:
    - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf 
    depends_on:
      - Elasticsearch
    ports:
    - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"    
    networks:
      - elk

  Kibana:
    image: docker.elastic.co/kibana/kibana:8.3.3
    container_name: kibana
    restart: always       
    ports:
    - '5601:5601'
    environment:
      ELASTICSEARCH_URL: "http://localhost:9200"
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"  
      elasticsearch.ssl.verificationMode: none  
      xpack.monitoring.ui.container.elasticsearch.enabled: "true" 
      LOGGING_VERBOSE: "true"
    depends_on:
      - elk
volumes:
  elastic_data: {}

networks:
  elk:
  