apiVersion: v1
kind: Pod
metadata:
  name: redisdb
spec:
  containers:
  - name: redisdb
    image: redis
    command:
      - redis-server
      - "/redis-master/redis.conf"
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: redis-configmap
        items:
        - key: redis-config
          path: redis.conf
---
apiVersion: v1
kind: Service
metadata:
  name: redisdb-service
spec:
  selector:
    app: redisdb
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  externalIPs:
    - 10.12.14.114